FROM python:3.12-slim

# crear carpeta de trabajo 
WORKDIR /app

# copia de requerimientos 
COPY requirements.txt .

# instalarlos
RUN pip install --no-cache-dir -r requirements.txt

# copiar codigo del proyecto
COPY . .

# exponer puerto a trabajar 
EXPOSE 5040

# Comandos para ejecutar flask
CMD ["python", "app.py"]
